from utils import *
from logic import *

def haz_clausulas(clauses):
    # Gripe
    clauses.append(expr("(TosPersistente(x) & TosSeca(x) & DificultadRespirar(x) & Cansancio(x) & Debilidad(x) & Congestion(x) & GoteoNasal(x) & DolorGarganta(x) & DolorOjos(x) & Fiebre(x) & DolorCabeza(x) & DolorMuscular(x) & Escalofrios(x) & Sudoracion(x)) ==> Gripe(x)"))
    clauses.append(expr("TosSeca(x) & DificultadRespirar(x) & Cansancio(x) & Debilidad(x) & Congestion(x) & GoteoNasal(x) & DolorGarganta(x) & DolorOjos(x) & Fiebre(x) & DolorCabeza(x) & DolorMuscular(x) & Escalofrios(x) & Sudoracion(x) ==> Gripe(x)"))
    clauses.append(expr("TosPersistente(x) & DificultadRespirar(x) & Cansancio(x) & Debilidad(x) & Congestion(x) & GoteoNasal(x) & DolorGarganta(x) & DolorOjos(x) & Fiebre(x) & DolorCabeza(x) & DolorMuscular(x) & Escalofrios(x) & Sudoracion(x) ==> Gripe(x)"))
    clauses.append(expr("TosPersistente(x) & TosSeca(x) & Cansancio(x) & Debilidad(x) & Congestion(x) & GoteoNasal(x) & DolorGarganta(x) & DolorOjos(x) & Fiebre(x) & DolorCabeza(x) & DolorMuscular(x) & Escalofrios(x) & Sudoracion(x) ==> Gripe(x)"))
    clauses.append(expr("TosPersistente(x) & TosSeca(x) & DificultadRespirar(x) & Debilidad(x) & Congestion(x) & GoteoNasal(x) & DolorGarganta(x) & DolorOjos(x) & Fiebre(x) & DolorCabeza(x) & DolorMuscular(x) & Escalofrios(x) & Sudoracion(x) ==> Gripe(x)"))
    clauses.append(expr("TosPersistente(x) & TosSeca(x) & DificultadRespirar(x) & Cansancio(x) & Congestion(x) & GoteoNasal(x) & DolorGarganta(x) & DolorOjos(x) & Fiebre(x) & DolorCabeza(x) & DolorMuscular(x) & Escalofrios(x) & Sudoracion(x) ==> Gripe(x)"))
    clauses.append(expr("TosPersistente(x) & TosSeca(x) & DificultadRespirar(x) & Cansancio(x) & Debilidad(x) & DolorGarganta(x) & DolorOjos(x) & Fiebre(x) & DolorCabeza(x) & DolorMuscular(x) & Escalofrios(x) & Sudoracion(x) ==> Gripe(x)"))
    clauses.append(expr("TosPersistente(x) & TosSeca(x) & DificultadRespirar(x) & Cansancio(x) & Debilidad(x) & Congestion(x) & GoteoNasal(x) & DolorOjos(x) & Fiebre(x) & DolorCabeza(x) & DolorMuscular(x) & Escalofrios(x) & Sudoracion(x) ==> Gripe(x)"))
    clauses.append(expr("TosPersistente(x) & TosSeca(x) & DificultadRespirar(x) & Cansancio(x) & Debilidad(x) & Congestion(x) & GoteoNasal(x) & DolorGarganta(x) & Fiebre(x) & DolorCabeza(x) & DolorMuscular(x) & Escalofrios(x) & Sudoracion(x) ==> Gripe(x)"))
    clauses.append(expr("TosPersistente(x) & TosSeca(x) & DificultadRespirar(x) & Cansancio(x) & Debilidad(x) & Congestion(x) & GoteoNasal(x) & DolorGarganta(x) & DolorOjos(x) & DolorCabeza(x) & DolorMuscular(x) & Escalofrios(x) & Sudoracion(x) ==> Gripe(x)"))
    clauses.append(expr("TosPersistente(x) & TosSeca(x) & DificultadRespirar(x) & Cansancio(x) & Debilidad(x) & Congestion(x) & GoteoNasal(x) & DolorGarganta(x) & DolorOjos(x) & Fiebre(x) & DolorMuscular(x) & Escalofrios(x) & Sudoracion(x) ==> Gripe(x)"))
    clauses.append(expr("TosPersistente(x) & TosSeca(x) & DificultadRespirar(x) & Cansancio(x) & Debilidad(x) & Congestion(x) & GoteoNasal(x) & DolorGarganta(x) & DolorOjos(x) & Fiebre(x) & DolorCabeza(x) & Escalofrios(x) & Sudoracion(x) ==> Gripe(x)"))
    clauses.append(expr("TosPersistente(x) & TosSeca(x) & DificultadRespirar(x) & Cansancio(x) & Debilidad(x) & Congestion(x) & GoteoNasal(x) & DolorGarganta(x) & DolorOjos(x) & Fiebre(x) & DolorCabeza(x) & DolorMuscular(x) & Sudoracion(x) ==> Gripe(x)"))
    clauses.append(expr("TosPersistente(x) & TosSeca(x) & DificultadRespirar(x) & Cansancio(x) & Debilidad(x) & Congestion(x) & GoteoNasal(x) & DolorGarganta(x) & DolorOjos(x) & Fiebre(x) & DolorCabeza(x) & DolorMuscular(x) & Escalofrios(x) ==> Gripe(x)"))

    # Covid
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Escalofrios(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DificultadRespirar(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & Nauseas(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Vomito(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Diarrea(x) ==> Covid19(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DificultadRespirar(x) & Fatiga(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & PerdidaRecienteDelOlfatoOGusto(x) & DolorGarganta(x) & Congestion(x) & GoteoNasal(x) & Nauseas(x) & Vomito(x) ==> Covid19(x)"))



    # Influenza
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DolorGarganta(x) & Congestion(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & Fatiga(x) & Vomito(x) & Diarrea(x) ==> Influenza(x)"))
    clauses.append(expr("Escalofrios(x) & Tos(x) & DolorGarganta(x) & Congestion(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & Fatiga(x) & Vomito(x) & Diarrea(x) ==> Influenza(x)"))
    clauses.append(expr("Fiebre(x) & Tos(x) & DolorGarganta(x) & Congestion(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & Fatiga(x) & Vomito(x) & Diarrea(x) ==> Influenza(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & DolorGarganta(x) & Congestion(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & Fatiga(x) & Vomito(x) & Diarrea(x) ==> Influenza(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & Congestion(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & Fatiga(x) & Vomito(x) & Diarrea(x) ==> Influenza(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DolorGarganta(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & Fatiga(x) & Vomito(x) & Diarrea(x) ==> Influenza(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DolorGarganta(x) & Congestion(x) & DolorCorporal(x) & DolorCabeza(x) & Fatiga(x) & Vomito(x) & Diarrea(x) ==> Influenza(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DolorGarganta(x) & Congestion(x) & DolorMuscular(x) & DolorCabeza(x) & Fatiga(x) & Vomito(x) & Diarrea(x) ==> Influenza(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DolorGarganta(x) & Congestion(x) & DolorMuscular(x) & DolorCorporal(x) & Fatiga(x) & Vomito(x) & Diarrea(x) ==> Influenza(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DolorGarganta(x) & Congestion(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & Vomito(x) & Diarrea(x) ==> Influenza(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DolorGarganta(x) & Congestion(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & Fatiga(x) & Diarrea(x) ==> Influenza(x)"))
    clauses.append(expr("Fiebre(x) & Escalofrios(x) & Tos(x) & DolorGarganta(x) & Congestion(x) & DolorMuscular(x) & DolorCorporal(x) & DolorCabeza(x) & Fatiga(x) & Vomito(x) ==> Influenza(x)"))


    # Fibrosis Pulmonar 
    clauses.append(expr("DificultadRespirar(x) & TosSeca(x) & TosPersistente(x) & RespiracionRapida(x) & PerdidaDePeso(x) & Cansancio(x) & DolorArticulaciones(x) & DolorMuscular(x) & Acropaquia(x) ==> FibrosisPulmonar(x)"))
    clauses.append(expr("TosSeca(x) & TosPersistente(x) & RespiracionRapida(x) & PerdidaDePeso(x) & Cansancio(x) & DolorArticulaciones(x) & DolorMuscular(x) & Acropaquia(x) ==> FibrosisPulmonar(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosPersistente(x) & RespiracionRapida(x) & PerdidaDePeso(x) & Cansancio(x) & DolorArticulaciones(x) & DolorMuscular(x) & Acropaquia(x) ==> FibrosisPulmonar(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosSeca(x) & RespiracionRapida(x) & PerdidaDePeso(x) & Cansancio(x) & DolorArticulaciones(x) & DolorMuscular(x) & Acropaquia(x) ==> FibrosisPulmonar(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosSeca(x) & TosPersistente(x) & PerdidaDePeso(x) & Cansancio(x) & DolorArticulaciones(x) & DolorMuscular(x) & Acropaquia(x) ==> FibrosisPulmonar(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosSeca(x) & TosPersistente(x) & RespiracionRapida(x) & Cansancio(x) & DolorArticulaciones(x) & DolorMuscular(x) & Acropaquia(x) ==> FibrosisPulmonar(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosSeca(x) & TosPersistente(x) & RespiracionRapida(x) & PerdidaDePeso(x) & DolorArticulaciones(x) & DolorMuscular(x) & Acropaquia(x) ==> FibrosisPulmonar(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosSeca(x) & TosPersistente(x) & RespiracionRapida(x) & PerdidaDePeso(x) & Cansancio(x) & DolorMuscular(x) & Acropaquia(x) ==> FibrosisPulmonar(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosSeca(x) & TosPersistente(x) & RespiracionRapida(x) & PerdidaDePeso(x) & Cansancio(x) & DolorArticulaciones(x) & Acropaquia(x) ==> FibrosisPulmonar(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosSeca(x) & TosPersistente(x) & RespiracionRapida(x) & PerdidaDePeso(x) & Cansancio(x) & DolorArticulaciones(x) & DolorMuscular(x) ==> FibrosisPulmonar(x)"))

    # Cáncer de Pulmón
    clauses.append(expr("DificultadRespirar(x) & TosConSangre(x) & TosPersistente(x) & Cansancio(x) & PerdidaDePeso(x) & PerdidaDeApetito(x) & DolorDePecho(x) & Ronquera(x) & DolorDehuesos(x) & DolorCabeza(x) ==> CancerPulmon(x)"))
    clauses.append(expr("TosConSangre(x) & TosPersistente(x) & Cansancio(x) & PerdidaDePeso(x) & PerdidaDeApetito(x) & DolorDePecho(x) & Ronquera(x) & DolorDehuesos(x) & DolorCabeza(x) ==> CancerPulmon(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosPersistente(x) & Cansancio(x) & PerdidaDePeso(x) & PerdidaDeApetito(x) & DolorDePecho(x) & Ronquera(x) & DolorDehuesos(x) & DolorCabeza(x) ==> CancerPulmon(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosConSangre(x) & Cansancio(x) & PerdidaDePeso(x) & PerdidaDeApetito(x) & DolorDePecho(x) & Ronquera(x) & DolorDehuesos(x) & DolorCabeza(x) ==> CancerPulmon(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosConSangre(x) & TosPersistente(x) & PerdidaDePeso(x) & PerdidaDeApetito(x) & DolorDePecho(x) & Ronquera(x) & DolorDehuesos(x) & DolorCabeza(x) ==> CancerPulmon(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosConSangre(x) & TosPersistente(x) & Cansancio(x) & PerdidaDeApetito(x) & DolorDePecho(x) & Ronquera(x) & DolorDehuesos(x) & DolorCabeza(x) ==> CancerPulmon(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosConSangre(x) & TosPersistente(x) & Cansancio(x) & PerdidaDePeso(x) & DolorDePecho(x) & Ronquera(x) & DolorDehuesos(x) & DolorCabeza(x) ==> CancerPulmon(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosConSangre(x) & TosPersistente(x) & Cansancio(x) & PerdidaDePeso(x) & PerdidaDeApetito(x) & Ronquera(x) & DolorDehuesos(x) & DolorCabeza(x) ==> CancerPulmon(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosConSangre(x) & TosPersistente(x) & Cansancio(x) & PerdidaDePeso(x) & PerdidaDeApetito(x) & DolorDePecho(x) & DolorDehuesos(x) & DolorCabeza(x) ==> CancerPulmon(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosConSangre(x) & TosPersistente(x) & Cansancio(x) & PerdidaDePeso(x) & PerdidaDeApetito(x) & DolorDePecho(x) & Ronquera(x) & DolorCabeza(x) ==> CancerPulmon(x)"))
    clauses.append(expr("DificultadRespirar(x) & TosConSangre(x) & TosPersistente(x) & Cansancio(x) & PerdidaDePeso(x) & PerdidaDeApetito(x) & DolorDePecho(x) & Ronquera(x) & DolorDehuesos(x) ==> CancerPulmon(x)"))

    # Bronquitis
    clauses.append(expr("TosConFlema(x) & TosSeca(x) & DolorDePecho(x) & Cansancio(x) & DolorCabeza(x) & DolorCorporal(x) & DolorGarganta(x) ==> Bronquitis(x)"))
    clauses.append(expr("TosSeca(x) & DolorDePecho(x) & Cansancio(x) & DolorCabeza(x) & DolorCorporal(x) & DolorGarganta(x) ==> Bronquitis(x)"))
    clauses.append(expr("TosConFlema(x) & DolorDePecho(x) & Cansancio(x) & DolorCabeza(x) & DolorCorporal(x) & DolorGarganta(x) ==> Bronquitis(x)"))
    clauses.append(expr("TosConFlema(x) & TosSeca(x) & Cansancio(x) & DolorCabeza(x) & DolorCorporal(x) & DolorGarganta(x) ==> Bronquitis(x)"))
    clauses.append(expr("TosConFlema(x) & TosSeca(x) & DolorDePecho(x) & DolorCabeza(x) & DolorCorporal(x) & DolorGarganta(x) ==> Bronquitis(x)"))
    clauses.append(expr("TosConFlema(x) & TosSeca(x) & DolorDePecho(x) & Cansancio(x) & DolorCorporal(x) & DolorGarganta(x) ==> Bronquitis(x)"))
    clauses.append(expr("TosConFlema(x) & TosSeca(x) & DolorDePecho(x) & Cansancio(x) & DolorCabeza(x) & DolorGarganta(x) ==> Bronquitis(x)"))
    clauses.append(expr("TosConFlema(x) & TosSeca(x) & DolorDePecho(x) & Cansancio(x) & DolorCabeza(x) & DolorCorporal(x) ==> Bronquitis(x)"))

    # Asma
    clauses.append(expr("DificultadRespirar(x) & SibilanciaAlExhalar(x) & ProblemasParaDormir(x) ==> Asma(x)"))
    clauses.append(expr("SibilanciaAlExhalar(x) & ProblemasParaDormir(x) ==> Asma(x)"))
    clauses.append(expr("DificultadRespirar(x) & ProblemasParaDormir(x) ==> Asma(x)"))
    clauses.append(expr("DificultadRespirar(x) & SibilanciaAlExhalar(x) ==> Asma(x)"))

    # Neumonia
    clauses.append(expr("Desorientacion(x) & TosConFlema(x) & TemperaturaBaja(x) & DificultadRespirar(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Nauseas(x) & Vomito(x) & Diarrea(x) & Escalofrios(x) & DolorDePecho(x) ==> Neumonia(x)"))
    clauses.append(expr("TosConFlema(x) & TemperaturaBaja(x) & DificultadRespirar(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Nauseas(x) & Vomito(x) & Diarrea(x) & Escalofrios(x) & DolorDePecho(x) ==> Neumonia(x)"))
    clauses.append(expr("Desorientacion(x) & TemperaturaBaja(x) & DificultadRespirar(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Nauseas(x) & Vomito(x) & Diarrea(x) & Escalofrios(x) & DolorDePecho(x) ==> Neumonia(x)"))
    clauses.append(expr("Desorientacion(x) & TosConFlema(x) & DificultadRespirar(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Nauseas(x) & Vomito(x) & Diarrea(x) & Escalofrios(x) & DolorDePecho(x) ==> Neumonia(x)"))
    clauses.append(expr("Desorientacion(x) & TosConFlema(x) & TemperaturaBaja(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Nauseas(x) & Vomito(x) & Diarrea(x) & Escalofrios(x) & DolorDePecho(x) ==> Neumonia(x)"))
    clauses.append(expr("Desorientacion(x) & TosConFlema(x) & TemperaturaBaja(x) & DificultadRespirar(x) & Sudoracion(x) & Fatiga(x) & Nauseas(x) & Vomito(x) & Diarrea(x) & Escalofrios(x) & DolorDePecho(x) ==> Neumonia(x)"))
    clauses.append(expr("Desorientacion(x) & TosConFlema(x) & TemperaturaBaja(x) & DificultadRespirar(x) & Fiebre(x) & Fatiga(x) & Nauseas(x) & Vomito(x) & Diarrea(x) & Escalofrios(x) & DolorDePecho(x) ==> Neumonia(x)"))
    clauses.append(expr("Desorientacion(x) & TosConFlema(x) & TemperaturaBaja(x) & DificultadRespirar(x) & Fiebre(x) & Sudoracion(x) & Nauseas(x) & Vomito(x) & Diarrea(x) & Escalofrios(x) & DolorDePecho(x) ==> Neumonia(x)"))
    clauses.append(expr("Desorientacion(x) & TosConFlema(x) & TemperaturaBaja(x) & DificultadRespirar(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Vomito(x) & Diarrea(x) & Escalofrios(x) & DolorDePecho(x) ==> Neumonia(x)"))
    clauses.append(expr("Desorientacion(x) & TosConFlema(x) & TemperaturaBaja(x) & DificultadRespirar(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Nauseas(x) & Diarrea(x) & Escalofrios(x) & DolorDePecho(x) ==> Neumonia(x)"))
    clauses.append(expr("Desorientacion(x) & TosConFlema(x) & TemperaturaBaja(x) & DificultadRespirar(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Nauseas(x) & Vomito(x) & Escalofrios(x) & DolorDePecho(x) ==> Neumonia(x)"))
    clauses.append(expr("Desorientacion(x) & TosConFlema(x) & TemperaturaBaja(x) & DificultadRespirar(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Nauseas(x) & Vomito(x) & Diarrea(x) & DolorDePecho(x) ==> Neumonia(x)"))
    clauses.append(expr("Desorientacion(x) & TosConFlema(x) & TemperaturaBaja(x) & DificultadRespirar(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Nauseas(x) & Vomito(x) & Diarrea(x) & Escalofrios(x) ==> Neumonia(x)"))

    # Apnea del sueño 
    clauses.append(expr("ProblemasDeMemoria(x) & EstadosDepresivos(x) & SomnolenciaDiurna(x) & SudoresNocturnos(x) & AumentoDePeso(x) & DisfuncionSexual(x) & DolorCabeza(x) & Fatiga(x) ==> Apnea(x)"))
    clauses.append(expr("EstadosDepresivos(x) & SomnolenciaDiurna(x) & SudoresNocturnos(x) & AumentoDePeso(x) & DisfuncionSexual(x) & DolorCabeza(x) & Fatiga(x) ==> Apnea(x)"))
    clauses.append(expr("ProblemasDeMemoria(x) & SomnolenciaDiurna(x) & SudoresNocturnos(x) & AumentoDePeso(x) & DisfuncionSexual(x) & DolorCabeza(x) & Fatiga(x) ==> Apnea(x)"))
    clauses.append(expr("ProblemasDeMemoria(x) & EstadosDepresivos(x) & SudoresNocturnos(x) & AumentoDePeso(x) & DisfuncionSexual(x) & DolorCabeza(x) & Fatiga(x) ==> Apnea(x)"))
    clauses.append(expr("ProblemasDeMemoria(x) & EstadosDepresivos(x) & SomnolenciaDiurna(x) & AumentoDePeso(x) & DisfuncionSexual(x) & DolorCabeza(x) & Fatiga(x) ==> Apnea(x)"))
    clauses.append(expr("ProblemasDeMemoria(x) & EstadosDepresivos(x) & SomnolenciaDiurna(x) & SudoresNocturnos(x) & DisfuncionSexual(x) & DolorCabeza(x) & Fatiga(x) ==> Apnea(x)"))
    clauses.append(expr("ProblemasDeMemoria(x) & EstadosDepresivos(x) & SomnolenciaDiurna(x) & SudoresNocturnos(x) & AumentoDePeso(x) & DolorCabeza(x) & Fatiga(x) ==> Apnea(x)"))
    clauses.append(expr("ProblemasDeMemoria(x) & EstadosDepresivos(x) & SomnolenciaDiurna(x) & SudoresNocturnos(x) & AumentoDePeso(x) & DisfuncionSexual(x) & Fatiga(x) ==> Apnea(x)"))
    clauses.append(expr("ProblemasDeMemoria(x) & EstadosDepresivos(x) & SomnolenciaDiurna(x) & SudoresNocturnos(x) & AumentoDePeso(x) & DisfuncionSexual(x) & DolorCabeza(x) ==> Apnea(x)"))

    # Tuberculosis
    clauses.append(expr("TosConFlema(x) & TosConSangre(x) & DolorAlRespirar(x) & DolorAlToser(x) & TosPersistente(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Escalofrios(x) & PerdidaDePeso(x) & DolorDePecho(x) & PerdidaDeApetito(x) ==> Tuberculosis(x)"))
    clauses.append(expr("TosConSangre(x) & DolorAlRespirar(x) & DolorAlToser(x) & TosPersistente(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Escalofrios(x) & PerdidaDePeso(x) & DolorDePecho(x) & PerdidaDeApetito(x) ==> Tuberculosis(x)"))
    clauses.append(expr("TosConFlema(x) & DolorAlRespirar(x) & DolorAlToser(x) & TosPersistente(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Escalofrios(x) & PerdidaDePeso(x) & DolorDePecho(x) & PerdidaDeApetito(x) ==> Tuberculosis(x)"))
    clauses.append(expr("TosConFlema(x) & TosConSangre(x) & DolorAlToser(x) & TosPersistente(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Escalofrios(x) & PerdidaDePeso(x) & DolorDePecho(x) & PerdidaDeApetito(x) ==> Tuberculosis(x)"))
    clauses.append(expr("TosConFlema(x) & TosConSangre(x) & DolorAlRespirar(x) & TosPersistente(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Escalofrios(x) & PerdidaDePeso(x) & DolorDePecho(x) & PerdidaDeApetito(x) ==> Tuberculosis(x)"))
    clauses.append(expr("TosConFlema(x) & TosConSangre(x) & DolorAlRespirar(x) & DolorAlToser(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Escalofrios(x) & PerdidaDePeso(x) & DolorDePecho(x) & PerdidaDeApetito(x) ==> Tuberculosis(x)"))
    clauses.append(expr("TosConFlema(x) & TosConSangre(x) & DolorAlRespirar(x) & DolorAlToser(x) & TosPersistente(x) & Sudoracion(x) & Fatiga(x) & Escalofrios(x) & PerdidaDePeso(x) & DolorDePecho(x) & PerdidaDeApetito(x) ==> Tuberculosis(x)"))
    clauses.append(expr("TosConFlema(x) & TosConSangre(x) & DolorAlRespirar(x) & DolorAlToser(x) & TosPersistente(x) & Fiebre(x) & Fatiga(x) & Escalofrios(x) & PerdidaDePeso(x) & DolorDePecho(x) & PerdidaDeApetito(x) ==> Tuberculosis(x)"))
    clauses.append(expr("TosConFlema(x) & TosConSangre(x) & DolorAlRespirar(x) & DolorAlToser(x) & TosPersistente(x) & Fiebre(x) & Sudoracion(x) & Escalofrios(x) & PerdidaDePeso(x) & DolorDePecho(x) & PerdidaDeApetito(x) ==> Tuberculosis(x)"))
    clauses.append(expr("TosConFlema(x) & TosConSangre(x) & DolorAlRespirar(x) & DolorAlToser(x) & TosPersistente(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & PerdidaDePeso(x) & DolorDePecho(x) & PerdidaDeApetito(x) ==> Tuberculosis(x)"))
    clauses.append(expr("TosConFlema(x) & TosConSangre(x) & DolorAlRespirar(x) & DolorAlToser(x) & TosPersistente(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Escalofrios(x) & DolorDePecho(x) & PerdidaDeApetito(x) ==> Tuberculosis(x)"))
    clauses.append(expr("TosConFlema(x) & TosConSangre(x) & DolorAlRespirar(x) & DolorAlToser(x) & TosPersistente(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Escalofrios(x) & PerdidaDePeso(x) & PerdidaDeApetito(x) ==> Tuberculosis(x)"))
    clauses.append(expr("TosConFlema(x) & TosConSangre(x) & DolorAlRespirar(x) & DolorAlToser(x) & TosPersistente(x) & Fiebre(x) & Sudoracion(x) & Fatiga(x) & Escalofrios(x) & PerdidaDePeso(x) & DolorDePecho(x) ==> Tuberculosis(x)"))

    # Tratamiento -----------------------------------------------
    # Camila
    clauses.append(expr("Gripe(x) & DolorMuscular(x) ==> Descanso(x)"))
    clauses.append(expr("Gripe(x) & DolorMuscular(x) ==> Hidratacion(x)"))
    clauses.append(expr("Gripe(x) & DolorMuscular(x) ==> Paracetamol(x)"))
    clauses.append(expr("Gripe(x) & DolorMuscular(x) ==> Ibuprofeno(x)"))
    clauses.append(expr("Gripe(x) & DolorMuscular(x) ==> AcidoAcetilsalicitico(x)"))
    clauses.append(expr("Gripe(x) & Fiebre(x) ==> Descanso(x)"))
    clauses.append(expr("Gripe(x) & Fiebre(x) ==> Hidratacion(x)"))
    clauses.append(expr("Gripe(x) & Fiebre(x) ==> Paracetamol(x)"))
    clauses.append(expr("Gripe(x) & Fiebre(x) ==> Ibuprofeno(x)"))
    clauses.append(expr("Gripe(x) & Fiebre(x) ==> AcidoAcetilsalicitico(x)"))
    clauses.append(expr("Gripe(x) & Congestion(x) ==> Clorfenamina(x)"))
    clauses.append(expr("Gripe(x) & Congestion(x) ==> Frenadol(x)"))
    clauses.append(expr("Gripe(x) & Congestion(x) ==> Couldina(x)"))
    clauses.append(expr("Gripe(x) & GoteoNasal(x) ==> Clorfenamina(x)"))
    clauses.append(expr("Gripe(x) & GoteoNasal(x) ==> Frenadol(x)"))
    clauses.append(expr("Gripe(x) & GoteoNasal(x) ==> Couldina(x)"))
    clauses.append(expr("Gripe(x) & TosSeca(x) ==> Dextrometorfano(x)"))
    clauses.append(expr("Neumonia(x) ==> Antibiotico(x)"))
    clauses.append(expr("Neumonia(x) ==> AcidoAcetilsalicitico(x)"))
    clauses.append(expr("Neumonia(x) ==> Ibuprofeno(x)"))
    clauses.append(expr("Neumonia(x) ==> Paracetamol(x)"))
    clauses.append(expr("CancerDePulmon(x) ==> Lobectomia(x)"))
    clauses.append(expr("CancerDePulmon(x) ==> Neumonectomia(x)"))
    clauses.append(expr("CancerDePulmon(x) ==> Segmentectomia(x)"))
    clauses.append(expr("CancerDePulmon(x) ==> ReseccionSegmentaria(x)"))
    clauses.append(expr("CancerDePulmon(x) ==> Radioterapia(x)"))
    clauses.append(expr("CancerDePulmon(x) ==> Quimioterapia(x)"))
    clauses.append(expr("CancerDePulmon(x) ==> RadioterapiaEstCorp(x)"))
    clauses.append(expr("CancerDePulmon(x) ==> TerapiaDirMed(x)"))
    clauses.append(expr("CancerDePulmon(x) ==> Inmunoterapia(x)"))
    clauses.append(expr("Tuberculosis(x) ==> Isoniacida(x)"))
    clauses.append(expr("Tuberculosis(x) ==> Rifampicina(x)"))
    clauses.append(expr("Tuberculosis(x) ==> Etambutol(x)"))
    clauses.append(expr("Tuberculosis(x) ==> Pirazinamida(x)"))

    # Karla

    clauses.append(expr("Asma(x) ==> CorticoidesInha(x)"))
    clauses.append(expr("Asma(x) ==> ModifLeucotrienos(x)"))
    clauses.append(expr("FibrosisPulmonar(x) ==> RehabPulmonar(x)"))
    clauses.append(expr("FibrosisPulmonar(x) ==> Pirfenidona(x)"))
    clauses.append(expr("FibrosisPulmonar(x) ==> Nintedanib(x)"))
    clauses.append(expr("FibrosisPulmonar(x) ==> TerapiaOxigeno(x)"))
    clauses.append(expr("Bronquitis(x) ==> Paracetamol(x)"))
    clauses.append(expr("Bronquitis(x) ==> AcidoAcetilsalicitico(x)"))
    clauses.append(expr("Bronquitis(x) ==> Descanso(x)"))
    clauses.append(expr("Bronquitis(x) ==> Hidratacion(x)"))

    # Victoria

    clauses.append(expr("Covid19(x) ==> Remdesivir(x)"))
    clauses.append(expr("Influenza(x) ==> Oseltamivir(x)"))
    clauses.append(expr("Influenza(x) ==> Zanamivir(x)"))
    clauses.append(expr("Influenza(x) ==> Peramivir(x)"))
    clauses.append(expr("Influenza(x) ==> Baloxavir(x)"))
    clauses.append(expr("Apnea(x) ==> RealizarEjercicio(x)"))
    clauses.append(expr("Apnea(x) ==> PesoSaludables(x)"))
    clauses.append(expr("Apnea(x) ==> LimitarAlcohol(x)"))
    clauses.append(expr("Apnea(x) ==> LimitarCafeina(x)"))
    clauses.append(expr("Apnea(x) ==> DejarFumar(x)"))
    clauses.append(expr("Apnea(x) ==> DormirBien(x)"))